name: Password check

on: [push]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install g++
        run: sudo apt-get install -y g++

      - name: Build
        run: g++ main.cpp -o main

      - name: Run
        env:
          PASSWORD: ${{secrets.PASSWORD}}
        run: ./main
